### ISSUE TITLE
Integrate current "show reputation" action into ACE interaction menu

### ISSUE THREAD

**Issue by xetra11** [CoopR-Mod/CoopR-Altis#2]
The player action *show action* is currenlty accessible through the action menu. If ACE is enabled it should be moved over to the ACE self interaction menu.

Therefore a new sub-menu "My Character" should be created as well.

Expected behaviour therefore is that a player can open his ace self interaction menu and select "My Character" > "Show Reputation"

**Comment by Katalam** [comment]
as in 5bea1ed said. No the player will have this ace action too. Fixed and Closed.

**Comment by xetra11** [comment]
Will be resolved in #3

**Comment by xetra11** [comment]
✔️  tested on dedicated
