### ISSUE TITLE
Add a function to manipulate ACE stamina of a player

### ISSUE THREAD

**Issue by xetra11** [CoopR-Mod/CoopR-Altis#4]
ACE stamina should be manipulated by a convenient function. The goal is to have a function ready to manipulate a players stamina for running etc.

example:

```
10 call myTag_fnc_raiseACE3Stamina;
4 call myTag_fnc_decreaseACE3Stamina;
16 call myTag_fnc_setACE3Stamina
```
ℹ️  functions signature must not match the example
ℹ️  functions should only work when ACE3 is enabled otherwise throw error

The goal is to raise the characters stamina level when he is for instance training in a gym ;)

**Comment by xetra11** [comment]
@Katalam 
So you actually just need to update the vanilla stamina and it applies to ace3 exhaustion system?

**Comment by Katalam** [comment]
Nah not really, but there are already functions to get and set the remaining stamina for a player. Also you can force walking or set the aiming coefficient.

**Comment by xetra11** [comment]
Ok so this issue seems to be superfluous. Thanks for your advice @Katalam
